export const frameworks = [
  {
    id: "prep",
    slug: "prep",
    name: "PREP",
    subtitle: "Point / Reason / Example / Point",
    summary: "A simple structure for sharing opinions clearly without overthinking.",
    bestFor: "Sharing an opinion with confidence.",
    whenToUse: "When you want to sound clear and grounded.",
    whyItHelps: "It keeps you focused so your message feels calm and complete.",
    examplePrompt: "What do you think about working remotely?",
    exampleAnswer: [
      "I really enjoy working remotely.",
      "It helps me focus better and manage my time.",
      "For example, I do not lose time commuting.",
      "So overall, it works really well for me.",
    ],
    practiceSteps: [
      { label: "Point", prompt: "What is your main opinion?" },
      { label: "Reason", prompt: "Why do you think that?" },
      { label: "Example", prompt: "Give a simple example." },
      { label: "Point again", prompt: "Restate your opinion naturally." },
    ],
    reflection: "Did your answer feel clearer than usual?",
    situationLabel: "I want to give my opinion clearly",
    practiceQuestions: [
      "Do you like working from home?",
      "Which do you prefer: coffee or tea?",
      "Is it better to wake up early or sleep late?",
      "Do you like to plan your day or be spontaneous?",
      "Should people reply to messages quickly?",
      "Is it okay to be late for small meetings?",
      "Do you prefer reading or watching movies?",
      "Is it better to live in a city or a small town?",
      "Should people exercise every day?",
      "Do you like cooking at home or eating out?",
      "Which is better: online shopping or in-store shopping?",
      "Is it important to take breaks during work?",
      "Do you prefer a quiet or a busy weekend?",
      "Should people save money or spend it on experiences?",
      "Do you like learning new languages?",
    ],
  },
  {
    id: "what-so-what-now-what",
    slug: "what-so-what-now-what",
    name: "What / So What / Now What",
    subtitle: "Explain / Make meaning / Decide next",
    summary: "A quick way to explain a situation without losing the main point.",
    bestFor: "Explaining something that happened.",
    whenToUse: "When someone asks for a recap or update.",
    whyItHelps: "It keeps your story focused and easy to follow.",
    examplePrompt: "Tell me about a recent challenge you had.",
    exampleAnswer: [
      "Last week I missed an important deadline.",
      "It made me realize I was taking on too much.",
      "Now I am trying to prioritize better.",
    ],
    practiceSteps: [
      { label: "What", prompt: "What happened?" },
      { label: "So What", prompt: "Why does this matter? What did I learn? How do I feel about it?" },
      { label: "Now What", prompt: "What will you do next?" },
    ],
    reflection: "Did your story feel more focused?",
    situationLabel: "I am explaining something that happened",
    practiceQuestions: [
      "Tell me about a small problem you had today.",
      "Describe a time you were late this week.",
      "Talk about a change at work or school.",
      "Tell me about a conversation that surprised you.",
      "Describe a time you forgot something important.",
      "Share a recent success, even a small one.",
      "Explain a time you had to change your plan.",
      "Tell me about a time you felt stressed recently.",
      "Describe a situation where you had to wait.",
      "Explain a time you asked for help.",
      "Tell me about a task that took longer than expected.",
      "Describe a time you learned something new.",
      "Explain a time you made a mistake and fixed it.",
      "Tell me about a time you had good news.",
      "Describe a time you felt proud of yourself.",
    ],
  },
  {
    id: "para",
    slug: "para",
    name: "PARA",
    subtitle: "Point / Action / Result / Ask",
    summary: "A calm way to explain a problem and ask for what you need.",
    bestFor: "Communicating without oversharing.",
    whenToUse: "When you want to be clear and respectful of time.",
    whyItHelps: "It helps you stay concise and ask with confidence.",
    examplePrompt: "You need help with a deadline.",
    exampleAnswer: [
      "I am having trouble meeting the deadline.",
      "I reorganized my schedule.",
      "I am still short on time.",
      "Could we extend it by two days?",
    ],
    practiceSteps: [
      { label: "Point", prompt: "What is the main issue?" },
      { label: "Action", prompt: "What did you do?" },
      { label: "Result", prompt: "What happened?" },
      { label: "Ask", prompt: "What do you need?" },
    ],
    reflection: "Did this help you avoid oversharing?",
    situationLabel: "I want to explain something without oversharing",
    practiceQuestions: [
      "Ask for more time on a deadline.",
      "Explain a delay without too many details.",
      "Ask for help with a task.",
      "Say you cannot join a meeting.",
      "Explain why you missed a message.",
      "Ask to reschedule a call.",
      "Say you need clarification on instructions.",
      "Explain a small mistake you made.",
      "Ask for an extension on a bill or payment.",
      "Say you are not available this weekend.",
      "Explain that you are working on it.",
      "Ask someone to repeat the last point.",
      "Say you need a short break.",
      "Explain why you are running late.",
      "Ask for feedback on your work.",
    ],
  },
  {
    id: "rase",
    slug: "rase",
    name: "RASE",
    subtitle: "Respond / Acknowledge / Understand / Encourage",
    summary: "A supportive structure for feedback and emotional conversations.",
    bestFor: "Handling feedback or emotions with care.",
    whenToUse: "When someone shares a concern or feeling.",
    whyItHelps: "It helps you sound steady and empathetic.",
    examplePrompt: "A friend says: \"I feel overwhelmed at work lately.\"",
    exampleAnswer: [
      "I am sorry you are feeling this way.",
      "It sounds like a lot is happening.",
      "Anyone would feel overwhelmed.",
      "Do you want to talk about it?",
    ],
    practiceSteps: [
      { label: "Respond", prompt: "What is your response?" },
      { label: "Acknowledge", prompt: "How do you acknowledge their feelings?" },
      { label: "Understand", prompt: "How do you show understanding?" },
      { label: "Encourage", prompt: "How do you keep the conversation open?" },
    ],
    reflection: "Did your response feel more empathetic?",
    situationLabel: "Someone is sharing a concern or giving feedback",
    practiceQuestions: [
      "A friend says they are stressed about work.",
      "Someone says they feel left out in a group.",
      "A coworker says the project is overwhelming.",
      "A friend says they are tired all the time.",
      "Someone says they made a mistake.",
      "A teammate says the deadline feels too tight.",
      "A friend says they are worried about money.",
      "Someone says they are nervous about a meeting.",
      "A friend says they feel unappreciated.",
      "A coworker says they are confused by feedback.",
      "A friend says they are feeling lonely.",
      "Someone says they are frustrated with a task.",
      "A friend says they are not confident about English.",
      "A teammate says they need support.",
      "A friend says they are having a bad day.",
    ],
  },
  {
    id: "4cs",
    slug: "4cs",
    name: "4 Cs",
    subtitle: "Connection / Context / Clarity / Conclusion",
    summary: "A mindful way to speak with intention in important moments.",
    bestFor: "Intentional conversations that matter to you.",
    whenToUse: "When you want to be honest and thoughtful.",
    whyItHelps: "It slows you down so your message feels intentional.",
    examplePrompt: "You want to have an honest conversation.",
    exampleAnswer: [
      "I really value our relationship.",
      "Lately, I have felt a bit disconnected.",
      "I want to be honest about that.",
      "I would like us to talk more openly.",
    ],
    practiceSteps: [
      { label: "Connection", prompt: "How can you create connection?" },
      { label: "Context", prompt: "What context is needed?" },
      { label: "Clarity", prompt: "What do you want to say?" },
      { label: "Conclusion", prompt: "How do you want to close?" },
    ],
    reflection: "Did this help you slow down before speaking?",
    situationLabel: "I want to speak more consciously",
    practiceQuestions: [
      "Start a difficult conversation with a friend.",
      "Share something important with your partner.",
      "Talk to a coworker about a misunderstanding.",
      "Speak to a friend you have not seen in a while.",
      "Tell someone you value their help.",
      "Say you want to improve your communication.",
      "Explain why a topic matters to you.",
      "Ask to have a calm conversation.",
      "Say you want to be more honest about your feelings.",
      "Bring up a concern in a respectful way.",
      "Say you want to listen better.",
      "Explain a boundary you need.",
      "Start a conversation about a shared goal.",
      "Say you want to reconnect.",
      "Ask for a moment to think before replying.",
    ],
  },
] as const

export type Framework = (typeof frameworks)[number]

export const frameworkById = Object.fromEntries(
  frameworks.map(framework => [framework.id, framework])
) as Record<string, Framework>
